"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Space, SpaceId } from "@/types";
import { SPACES } from "@/data/mock";
import { SpaceMap } from "@/components/space-map";
import { Trash2, Plus, Save, Database, Layout, Copy } from "lucide-react";

interface AdminSettingsDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

export function AdminSettingsDialog({ open, onOpenChange }: AdminSettingsDialogProps) {
    const [spaces, setSpaces] = useState<Space[]>(SPACES);
    const [selectedId, setSelectedId] = useState<SpaceId | null>(null);

    // Database Config State
    const [dbConfig, setDbConfig] = useState({
        host: "",
        user: "",
        password: "",
        database: "",
        port: "3306"
    });

    const selectedSpace = spaces.find(s => s.id === selectedId);

    const updateSpace = (id: SpaceId, updates: Partial<Space> | Partial<Space["mapConfig"]>) => {
        setSpaces(prev => prev.map(s => {
            if (s.id !== id) return s;
            const isMapConfig = 'x' in updates || 'y' in updates || 'width' in updates || 'height' in updates;
            if (isMapConfig) {
                return { ...s, mapConfig: { ...s.mapConfig, ...updates } };
            }
            return { ...s, ...updates };
        }));
    };

    const handleAddSpace = () => {
        const newId = `space-${Date.now()}` as SpaceId;
        const newSpace: Space = {
            id: newId,
            name: "Nuevo Espacio",
            description: "",
            dimensions: "0x0m",
            type: "indoor",
            hourlyRate: 0,
            color: "bg-gray-500",
            mapConfig: { x: 10, y: 10, width: 50, height: 50, borderRadius: 0 }
        };
        setSpaces([...spaces, newSpace]);
        setSelectedId(newId);
    };

    // Fetch spaces on mount
    useState(() => {
        fetch('/api/spaces')
            .then(res => res.json())
            .then(data => {
                if (Array.isArray(data)) setSpaces(data);
            })
            .catch(err => console.error("Failed to load spaces", err));
    });

    const handleSaveSpaces = async () => {
        try {
            // Save each space. In a real bulk update, we might want a bulk endpoint.
            // For now, we update the modified one or all.
            // Optimization: Just update the selected Space if any, or all.
            // Given the valid concern of "saving configuration", let's save ALL current spaces or just the tracked changes.
            // Simpler approach for this "Config Panel": Save the currently selected space if editing, or iterating all is safer but slower.

            // To be precise with the user request "fix create new space", we need to ensure NEW spaces (no ID in DB?) are POSTed.
            // Our "handleAddSpace" generates a temp ID. We should check if it exists in DB or not.
            // A clearer way: The "Save" button usually applies to the form being edited.

            if (selectedSpace) {
                const method = selectedSpace.id.startsWith('space-') ? 'POST' : 'PUT'; // Heuristic: temp IDs start with space-

                // If it's a new space, we might want to remove the temporary ID and let DB/Backend assign one, 
                // OR keep the UUID generated by frontend (mock one matches uuid format? No, 'space-...' is not uuid).
                // Prisma is configured to generate UUIDs (@default(uuid())). 
                // So if we send ID for POST, it might be used. But 'space-time' is not UUID.
                // We should probably strip ID for POST if it's not a valid UUID, or let backend handle it.
                // Let's strip it.

                const body = { ...selectedSpace };
                if (method === 'POST') {
                    // @ts-ignore
                    delete body.id;
                }

                const res = await fetch('/api/spaces', {
                    method,
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(body)
                });

                if (res.ok) {
                    const saved = await res.json();
                    // Update state with distinct saved data (especially real ID)
                    setSpaces(prev => prev.map(s => s.id === selectedSpace.id ? saved : s));
                    if (selectedSpace.id !== saved.id) setSelectedId(saved.id); // Update selection to new ID
                    alert("Espacio guardado correctamente.");
                } else {
                    alert("Error al guardar espacio.");
                }
            }
        } catch (error) {
            console.error(error);
            alert("Error de conexión al guardar.");
        }
    };

    const handleDeleteSpace = async (id: SpaceId) => {
        if (confirm("¿Estás seguro de eliminar este espacio?")) {
            try {
                // If it's a local-only new space
                if (id.startsWith('space-')) {
                    setSpaces(spaces.filter(s => s.id !== id));
                    if (selectedId === id) setSelectedId(null);
                    return;
                }

                const res = await fetch(`/api/spaces?id=${id}`, { method: 'DELETE' });
                if (res.ok) {
                    setSpaces(spaces.filter(s => s.id !== id));
                    if (selectedId === id) setSelectedId(null);
                } else {
                    alert("Error al eliminar espacio.");
                }
            } catch (error) {
                console.error(error);
                alert("Error de conexión al eliminar.");
            }
        }
    };

    const handleSaveDb = () => {
        console.log("Saving DB config:", dbConfig);
        alert("Configuración de base de datos guardada (Simulación).");
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto flex flex-col">
                <DialogHeader>
                    <DialogTitle>Configuración del Sistema</DialogTitle>
                    <DialogDescription>
                        Administra los espacios, ubicación y conexión a base de datos.
                    </DialogDescription>
                </DialogHeader>

                <Tabs defaultValue="spaces" className="w-full flex-1 flex flex-col mt-4">
                    <TabsList className="grid w-full grid-cols-2 mb-4">
                        <TabsTrigger value="spaces" className="gap-2">
                            <Layout className="w-4 h-4" /> Espacios y Mapa
                        </TabsTrigger>
                        <TabsTrigger value="database" className="gap-2">
                            <Database className="w-4 h-4" /> Base de Datos (Producción)
                        </TabsTrigger>
                    </TabsList>

                    <TabsContent value="spaces" className="flex-1">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {/* Left: Map Preview & List */}
                            <div className="space-y-4">
                                <div className="border rounded-md p-2 bg-muted/20">
                                    <label className="text-xs font-semibold uppercase text-muted-foreground mb-2 block">Vista Previa</label>
                                    <SpaceMap spaces={spaces} selectedSpaceId={selectedId || undefined} onSelect={setSelectedId} />
                                    <p className="text-xs text-muted-foreground mt-2 text-center">
                                        Haz clic en un espacio para editarlo
                                    </p>
                                </div>

                                <div className="border rounded-md p-2 h-48 overflow-y-auto">
                                    <div className="flex justify-between items-center mb-2 px-2">
                                        <label className="text-xs font-semibold uppercase text-muted-foreground">Lista de Espacios</label>
                                        <Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={handleAddSpace}><Plus className="w-4 h-4" /></Button>
                                    </div>
                                    <div className="space-y-1">
                                        {spaces.map(s => (
                                            <div
                                                key={s.id}
                                                onClick={() => setSelectedId(s.id)}
                                                className={`p-2 rounded text-sm cursor-pointer flex justify-between items-center ${selectedId === s.id ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'}`}
                                            >
                                                <span>{s.name}</span>
                                                {selectedId === s.id && <Trash2 className="w-3 h-3 cursor-pointer opacity-70 hover:opacity-100" onClick={(e) => { e.stopPropagation(); handleDeleteSpace(s.id); }} />}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Right: Edit Form */}
                            <div className="space-y-4 border-l pl-6">
                                {selectedSpace ? (
                                    <>
                                        <div className="flex items-center justify-between">
                                            <h3 className="font-bold text-lg">Editar: {selectedSpace.name}</h3>
                                        </div>

                                        <div className="space-y-3">
                                            <div className="space-y-1">
                                                <label className="text-xs font-medium">Nombre</label>
                                                <Input value={selectedSpace.name} onChange={e => updateSpace(selectedSpace.id, { name: e.target.value })} />
                                            </div>
                                            <div className="space-y-1">
                                                <label className="text-xs font-medium">Descripción</label>
                                                <Textarea value={selectedSpace.description} onChange={e => updateSpace(selectedSpace.id, { description: e.target.value })} className="h-20" />
                                            </div>
                                            <div className="grid grid-cols-2 gap-3">
                                                <div className="space-y-1">
                                                    <label className="text-xs font-medium">Tarifa ($/hr)</label>
                                                    <Input type="number" value={selectedSpace.hourlyRate} onChange={e => updateSpace(selectedSpace.id, { hourlyRate: Number(e.target.value) })} />
                                                </div>
                                                <div className="space-y-1">
                                                    <label className="text-xs font-medium">Tipo</label>
                                                    <Input value={selectedSpace.type} disabled />
                                                </div>
                                            </div>

                                            <div className="pt-4 border-t">
                                                <h4 className="font-semibold text-sm mb-3">Posición en Mapa</h4>
                                                <div className="grid grid-cols-2 gap-3">
                                                    <div className="space-y-1">
                                                        <label className="text-xs font-medium">Posición X</label>
                                                        <Input type="number" value={selectedSpace.mapConfig.x} onChange={e => updateSpace(selectedSpace.id, { x: Number(e.target.value) })} />
                                                    </div>
                                                    <div className="space-y-1">
                                                        <label className="text-xs font-medium">Posición Y</label>
                                                        <Input type="number" value={selectedSpace.mapConfig.y} onChange={e => updateSpace(selectedSpace.id, { y: Number(e.target.value) })} />
                                                    </div>
                                                    <div className="space-y-1">
                                                        <label className="text-xs font-medium">Ancho</label>
                                                        <Input type="number" value={selectedSpace.mapConfig.width} onChange={e => updateSpace(selectedSpace.id, { width: Number(e.target.value) })} />
                                                    </div>
                                                    <div className="space-y-1">
                                                        <label className="text-xs font-medium">Alto</label>
                                                        <Input type="number" value={selectedSpace.mapConfig.height} onChange={e => updateSpace(selectedSpace.id, { height: Number(e.target.value) })} />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <Button onClick={handleSaveSpaces} className="w-full mt-4 gap-2">
                                            <Save className="w-4 h-4" /> Guardar Cambios en Espacios
                                        </Button>
                                    </>
                                ) : (
                                    <div className="h-full flex flex-col items-center justify-center text-muted-foreground opacity-50">
                                        <p>Selecciona un espacio para editar</p>
                                    </div>
                                )}
                            </div>
                        </div>
                    </TabsContent>

                    <TabsContent value="database">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                            <div className="space-y-4">
                                <h3 className="font-bold text-lg flex items-center gap-2">
                                    <Database className="w-5 h-5" />
                                    Credenciales de Producción (MySQL)
                                </h3>
                                <p className="text-sm text-muted-foreground">
                                    Ingresa aquí los datos de tu base de datos creada en cPanel (MySQL).
                                    Esta configuración se usará para generar el archivo de conexión en producción.
                                </p>

                                <div className="space-y-3 border p-4 rounded-md">
                                    <div className="space-y-1">
                                        <label className="text-xs font-medium">Host (Servidor)</label>
                                        <Input
                                            placeholder="localhost o IP del servidor"
                                            value={dbConfig.host}
                                            onChange={e => setDbConfig({ ...dbConfig, host: e.target.value })}
                                        />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-xs font-medium">Nombre de Base de Datos</label>
                                        <Input
                                            placeholder="ej. u12345_casajavorai"
                                            value={dbConfig.database}
                                            onChange={e => setDbConfig({ ...dbConfig, database: e.target.value })}
                                        />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-xs font-medium">Usuario</label>
                                        <Input
                                            placeholder="ej. u12345_admin"
                                            value={dbConfig.user}
                                            onChange={e => setDbConfig({ ...dbConfig, user: e.target.value })}
                                        />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-xs font-medium">Contraseña</label>
                                        <Input
                                            type="password"
                                            placeholder="************"
                                            value={dbConfig.password}
                                            onChange={e => setDbConfig({ ...dbConfig, password: e.target.value })}
                                        />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-xs font-medium">Puerto</label>
                                        <Input
                                            value={dbConfig.port}
                                            onChange={e => setDbConfig({ ...dbConfig, port: e.target.value })}
                                        />
                                    </div>

                                    <Button onClick={handleSaveDb} className="w-full gap-2 mt-2">
                                        <Save className="w-4 h-4" /> Guardar Configuración de Conexión
                                    </Button>
                                </div>
                            </div>

                            <div className="space-y-4">
                                <h3 className="font-bold text-lg">Instrucciones de Despliegue (cPanel)</h3>
                                <div className="space-y-4 text-sm text-muted-foreground border rounded-md p-4 bg-muted/20">
                                    <p>1. <strong>Crea la Base de Datos:</strong> En tu cPanel, ve a "Bases de Datos MySQL" y crea una nueva base de datos y un usuario. Asígnalos y guarda los datos en el formulario de la izquierda.</p>

                                    <p>2. <strong>Variable de Entorno:</strong> Copia la siguiente cadena de conexión y pégala en el archivo <code>.env</code> en tu servidor (o administrador de archivos):</p>

                                    <div className="relative group">
                                        <code className="block bg-black text-white p-3 rounded text-xs break-all">
                                            DATABASE_URL="mysql://{dbConfig.user || 'USUARIO'}:{dbConfig.password || 'PASSWORD'}@{dbConfig.host || 'localhost'}:{dbConfig.port}/{dbConfig.database || 'DB_NAME'}"
                                        </code>
                                    </div>

                                    <p>3. <strong>Sube los Archivos:</strong> Sube tu proyecto a la carpeta <code>public_html</code> (o subdominio).</p>

                                    <p>4. <strong>Migración:</strong> Ejecuta el comando de prisma para crear las tablas si tienes acceso a terminal SSH, o contacta a soporte.</p>
                                </div>

                                <div className="bg-blue-50 border border-blue-200 p-3 rounded text-blue-800 text-xs">
                                    <strong>Nota:</strong> Actualmente estamos usando <strong>SQLite</strong> para este entorno de desarrollo local, por lo que no necesitas configurar esto para probar ahora. Esto es solo para cuando lo subas a Namecheap.
                                </div>
                            </div>
                        </div>
                    </TabsContent>
                </Tabs>

                <DialogFooter className="mt-auto pt-4 border-t">
                    <Button variant="outline" onClick={() => onOpenChange(false)}>Cerrar Panel</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
